#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
#include "SGL_Builtins/SGL_Structs.hpp"
#include "SGL_Window/SGL_Window.hpp"
#include "SGL_Font/SGL_Font.hpp"
#include "SGL_EventHandler/SGL_EventHandler.hpp"
#include "SGL_Clock/SGL_Clock.hpp"
#include "SGL_Parent/SGL_Parent.hpp"
#include "SGL_Widget/SGL_Widget.hpp"
#include "SGL_Label/SGL_Label.hpp"
#include "SGL_Button/SGL_Button.hpp"